@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR

Package Logic as LogicPackage <<Rectangle>>{
Class "<<interface>>\nCommand" as Command
Class "<<interface>>\nParser" as Parser
Class "<<interface>>\nLogic" as Logic
Class LogicManager
Class HelpCommand
Class CommandResult

Logic -down-> Parser
Logic -down-> Command
Logic -right-> CommandResult
LogicManager .up.|> Logic
LogicManager -down-> Parser
LogicManager -down-> Command

HelpCommand .up.|> Command
HelpCommand -right-> CommandResult

Parser -[hidden]down-> HelpCommand
}

Package Ui as UiPackage <<Rectangle>>{
Class MainWindow
Class HelpWindow
}

MainWindow -right-> Logic
MainWindow -down-> HelpWindow
HelpWindow -up-> CommandResult

@enduml