@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command has parameters])
    :Create a new predicate;
    :Filter the addressbook
    using the predicate;
    :Show the filtered contacts;
else ([else])
    : Show all contacts;
endif
stop
@enduml
